theme: jekyll-theme-tactile
title: Nexial Automation
description: Test Automation Platform for everyone!

plugins:
   - jekyll-mentions
   - jemoji
   - jekyll-redirect-from
   - jekyll-sitemap
   - jekyll-feed
   - jekyll-seo-tag
   - jekyll-avatar

show_downloads: false

google_analytics: UA-116385736-1

# Tipue search settings
tipue_search:
  include:
    pages: true
  exclude:
    files: [search.html]
#tipue_search_active: false
tipue_search_active: true

#breadcrumbs: true
#breadcrumb_display: true
#breadcrumb_home_display: true

read_more: enabled
comments: disque
favicon: favicon.ico
use_logo: true
logo: image/logo-small.png

#search_in_topnav: true
#search_in_sidebar: false
#toggle-sidebar-button: true
navbar-toggle: true

sidebars:
  - generic
  - jekyllhowto
link_type: jurl

# show feedback button in top nav bar?
show_feedback: true
feedback_email: mikeliucc@users.noreply.github.com

github_button_location_top_navbar: false
github_button_location_below_title: false
github_button_location_page_bottom: false
